# Generated by Django 4.1.4 on 2022-12-28 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='is_accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
